//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoDurban.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Association
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Association()
        {
            this.Payments = new HashSet<Payment>();
            this.tbl_AssociationLeadership = new HashSet<tbl_AssociationLeadership>();
            this.tbl_AssociationRegion = new HashSet<tbl_AssociationRegion>();
            this.tbl_AssociationServiceArea = new HashSet<tbl_AssociationServiceArea>();
            this.tbl_OwnerAssociation = new HashSet<tbl_OwnerAssociation>();
        }
    
        public int AssociationID { get; set; }
        public string AssociationName { get; set; }
        public string AssociationNo { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> AccountID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual tbl_Status tbl_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AssociationLeadership> tbl_AssociationLeadership { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AssociationRegion> tbl_AssociationRegion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AssociationServiceArea> tbl_AssociationServiceArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OwnerAssociation> tbl_OwnerAssociation { get; set; }
    }
}
