//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoDurban.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Date
    {
        public int DateID { get; set; }
        public System.DateTime Date1 { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int Day { get; set; }
        public int QuarterNumber { get; set; }
        public string keydate { get; set; }
        public string month_name { get; set; }
    }
}
