//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoDurban.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoOfClicksPerMonth
    {
        public int NoOfClicksID { get; set; }
        public string IsPaymentSent { get; set; }
        public Nullable<int> MonthClicked { get; set; }
        public string ColumnName { get; set; }
        public string RangeDate { get; set; }
    }
}
