//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoDurban.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> UserID { get; set; }
        public string TransNo { get; set; }
        public string LineNo { get; set; }
        public string BatchNo { get; set; }
        public string DocTy { get; set; }
        public string SP { get; set; }
        public string STSCD { get; set; }
        public string LongAddress { get; set; }
        public string AccountName { get; set; }
        public string AccountNo { get; set; }
        public string IDIssuer { get; set; }
        public string ID1Code { get; set; }
        public string TaxID { get; set; }
        public string PhoneNo { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string AddressLine4 { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string DocNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string AddressNo { get; set; }
        public string PaymentMethod { get; set; }
        public string BankName { get; set; }
        public string BankTransit { get; set; }
        public string BankAccNo { get; set; }
        public string IsPaymentSent { get; set; }
        public Nullable<bool> VoidedPayment { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<int> AssociationID { get; set; }
        public string EntityType { get; set; }
    
        public virtual Association Association { get; set; }
        public virtual Region Region { get; set; }
        public virtual tbl_Owner tbl_Owner { get; set; }
    }
}
