//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoDurban.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Driver
    {
        public int DriverID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string IDNo { get; set; }
        public Nullable<System.DateTime> CalcBirthDate { get; set; }
        public string CellNo { get; set; }
        public string OfficeNo { get; set; }
        public string Email { get; set; }
        public string AddressStreet { get; set; }
        public string AddressSuburb { get; set; }
        public string AddressCity { get; set; }
        public string AddressCode { get; set; }
        public Nullable<int> DriverLicenseScanID { get; set; }
        public Nullable<int> LicenseCodeID { get; set; }
        public Nullable<System.DateTime> LicenseExpiry { get; set; }
        public Nullable<int> PRDPScanID { get; set; }
        public string PRDPCode { get; set; }
        public Nullable<System.DateTime> PRDPExpiry { get; set; }
        public string EmploymentContract { get; set; }
        public Nullable<System.DateTime> EmploymentContractExpiry { get; set; }
        public Nullable<int> EmploymentContractScanID { get; set; }
        public Nullable<int> RecommendationLetterScanID { get; set; }
        public string CalcDriverNO { get; set; }
        public Nullable<bool> TermsAndConditions { get; set; }
        public Nullable<bool> ReviewContract { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> RaceID { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public Nullable<int> ReasonID { get; set; }
    
        public virtual tbl_Gender tbl_Gender { get; set; }
        public virtual tbl_Race tbl_Race { get; set; }
        public virtual tbl_Reason tbl_Reason { get; set; }
        public virtual tbl_Status tbl_Status { get; set; }
    }
}
