//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoDurban.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PaymentAmount
    {
        public int PaymentAmountID { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public string Recipients { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
