//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoDurban.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Vehicle
    {
        public int VehicleID { get; set; }
        public string NumberPlate { get; set; }
        public Nullable<System.DateTime> LastServiced { get; set; }
        public string YearRegistered { get; set; }
        public string EngineNumber { get; set; }
        public string VINNumber { get; set; }
        public Nullable<bool> CORScanID { get; set; }
        public Nullable<System.DateTime> CORExpiry { get; set; }
        public string OperatingLicense { get; set; }
        public Nullable<System.DateTime> OperatingLicenseExpiry { get; set; }
        public string VehicleAccreditation { get; set; }
        public string Year { get; set; }
        public string Capacity { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public Nullable<int> VehicleInfoID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> ReasonID { get; set; }
        public Nullable<bool> PaymentAdded { get; set; }
    
        public virtual tbl_Owner tbl_Owner { get; set; }
        public virtual tbl_Reason tbl_Reason { get; set; }
        public virtual tbl_Status tbl_Status { get; set; }
        public virtual tbl_VehicleInfo tbl_VehicleInfo { get; set; }
    }
}
