//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoDurban.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AuditTrail
    {
        public int Id { get; set; }
        public string TableName { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Actions { get; set; }
        public string OldData { get; set; }
        public string NewData { get; set; }
        public string ChangedColums { get; set; }
        public string TableIdValue { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
