//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoDurban.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DriverCount
    {
        public int org_process_id { get; set; }
        public int seq_id { get; set; }
        public string seq_name { get; set; }
        public Nullable<long> last_value { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> year { get; set; }
        public byte[] sys_timestamp { get; set; }
        public string inserted_user { get; set; }
        public Nullable<System.DateTime> inserted_date { get; set; }
        public string updated_user { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<long> hkey_id { get; set; }
    }
}
