//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoDurban.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Owner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Owner()
        {
            this.Payments = new HashSet<Payment>();
            this.tbl_OwnerAssociation = new HashSet<tbl_OwnerAssociation>();
            this.tbl_OwnerServiceArea = new HashSet<tbl_OwnerServiceArea>();
            this.tbl_Vehicle = new HashSet<tbl_Vehicle>();
        }
    
        public int OwnerID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string IDNo { get; set; }
        public Nullable<System.DateTime> CalcBirthDate { get; set; }
        public string CellNo { get; set; }
        public string OfficeNo { get; set; }
        public string Email { get; set; }
        public string AddressStreet { get; set; }
        public string AddressSuburb { get; set; }
        public string AddressCity { get; set; }
        public string AddressCode { get; set; }
        public string CompanyName { get; set; }
        public Nullable<bool> TermsAndConditions { get; set; }
        public Nullable<bool> ReviewContract { get; set; }
        public Nullable<int> RaceID { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> ReasonID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<bool> PendingDriver { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual tbl_Gender tbl_Gender { get; set; }
        public virtual tbl_Race tbl_Race { get; set; }
        public virtual tbl_Reason tbl_Reason { get; set; }
        public virtual tbl_Status tbl_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OwnerAssociation> tbl_OwnerAssociation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OwnerServiceArea> tbl_OwnerServiceArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Vehicle> tbl_Vehicle { get; set; }
    }
}
