//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoDurban.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LicenseCode
    {
        public int LicenseCodeID { get; set; }
        public string LicenseCode { get; set; }
        public string LicenseCodeDescription { get; set; }
    }
}
