//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoDurban.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AssociationLeadership
    {
        public int AssociationLeaderID { get; set; }
        public Nullable<int> AssociationID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string IDNo { get; set; }
        public string Passport { get; set; }
        public Nullable<bool> IsPassport { get; set; }
        public Nullable<System.DateTime> CalcBirthDate { get; set; }
        public string CellNo { get; set; }
        public string OfficeNo { get; set; }
        public string Email { get; set; }
        public int RaceID { get; set; }
        public int GenderID { get; set; }
        public string AddressStreet { get; set; }
        public string AddressSuburb { get; set; }
        public string AddressCity { get; set; }
        public Nullable<decimal> AddressCode { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<bool> TermsAndConditions { get; set; }
        public Nullable<bool> ReviewContract { get; set; }
        public Nullable<int> ReasonID { get; set; }
    
        public virtual Association Association { get; set; }
        public virtual tbl_Gender tbl_Gender { get; set; }
        public virtual tbl_Race tbl_Race { get; set; }
        public virtual tbl_Reason tbl_Reason { get; set; }
        public virtual tbl_Status tbl_Status { get; set; }
    }
}
