//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoDurban.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_details
    {
        public int accountid { get; set; }
        public string AccountName { get; set; }
        public string AccountNo { get; set; }
        public Nullable<int> regionid { get; set; }
        public Nullable<int> associationid { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public string IDNo { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string IsPaymentSent { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> tDate { get; set; }
        public string month_name { get; set; }
        public Nullable<int> P_amount { get; set; }
        public string RegionName { get; set; }
        public string associationname { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string NumberPlate { get; set; }
        public Nullable<int> cnt { get; set; }
    }
}
