//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoDurban.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_drivers
    {
        public int ownerid { get; set; }
        public string idno { get; set; }
        public string Oname { get; set; }
        public string Osurn { get; set; }
        public string RegionName { get; set; }
        public string associationname { get; set; }
        public Nullable<System.DateTime> ldate { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string DId { get; set; }
        public Nullable<int> statusid { get; set; }
        public Nullable<int> ReasonID { get; set; }
        public Nullable<int> DriverID { get; set; }
        public string ReasonDescription { get; set; }
        public string StatusDescription { get; set; }
        public string LicenseCodeDescription { get; set; }
        public Nullable<System.DateTime> LicenseExpiry { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
    }
}
