//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoDurban.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_region
    {
        public string regions { get; set; }
        public string IsPaymentSent { get; set; }
        public Nullable<int> P_amount { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
        public System.DateTime Date { get; set; }
        public string month_name { get; set; }
    }
}
