//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoDurban.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_vehicle
    {
        public int ownerid { get; set; }
        public string idno { get; set; }
        public string Name { get; set; }
        public string surname { get; set; }
        public string RegionName { get; set; }
        public string associationname { get; set; }
        public Nullable<System.DateTime> ldate { get; set; }
        public string NumberPlate { get; set; }
        public Nullable<int> statusid { get; set; }
        public Nullable<int> ReasonID { get; set; }
        public Nullable<System.DateTime> LastServiced { get; set; }
        public string OperatingLicense { get; set; }
        public Nullable<System.DateTime> OperatingLicenseExpiry { get; set; }
        public string ReasonDescription { get; set; }
        public string StatusDescription { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
    }
}
