//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoDurban.SharepointService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tibco.com/schemas/ism-document-management-service/SharedResources/Sche" +
        "mas/Error.xsd")]
    public partial class Error_T : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("ErrorDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.example.com/1459432320734", ConfigurationName="SharepointService.DocumentManagementSystem")]
    public interface DocumentManagementSystem {
        
        // CODEGEN: Generating message contract since the operation UploadDocument is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/webservice/Service/Service.serviceagent/DocumentManagementSystemEndpoint1/Upload" +
            "Document", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(GoDurban.SharepointService.Error_T), Action="/webservice/Service/Service.serviceagent/DocumentManagementSystemEndpoint1/Upload" +
            "Document", Name="Error", Namespace="http://www.tibco.com/schemas/ism-document-management-service/SharedResources/Sche" +
            "mas/Error.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GoDurban.SharepointService.UploadDocumentResponse UploadDocument(GoDurban.SharepointService.UploadDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/webservice/Service/Service.serviceagent/DocumentManagementSystemEndpoint1/Upload" +
            "Document", ReplyAction="*")]
        System.Threading.Tasks.Task<GoDurban.SharepointService.UploadDocumentResponse> UploadDocumentAsync(GoDurban.SharepointService.UploadDocumentRequest request);
        
        // CODEGEN: Generating message contract since the operation SearchDocument is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/webservice/Service/Service.serviceagent/DocumentManagementSystemEndpoint1/Search" +
            "Document", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(GoDurban.SharepointService.Error_T), Action="/webservice/Service/Service.serviceagent/DocumentManagementSystemEndpoint1/Search" +
            "Document", Name="Error", Namespace="http://www.tibco.com/schemas/ism-document-management-service/SharedResources/Sche" +
            "mas/Error.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GoDurban.SharepointService.SearchDocumentResponse SearchDocument(GoDurban.SharepointService.SearchDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/webservice/Service/Service.serviceagent/DocumentManagementSystemEndpoint1/Search" +
            "Document", ReplyAction="*")]
        System.Threading.Tasks.Task<GoDurban.SharepointService.SearchDocumentResponse> SearchDocumentAsync(GoDurban.SharepointService.SearchDocumentRequest request);
        
        // CODEGEN: Generating message contract since the operation DownloadDocument is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/webservice/Service/Service.serviceagent/DocumentManagementSystemEndpoint1/Downlo" +
            "adDocument", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(GoDurban.SharepointService.Error_T), Action="/webservice/Service/Service.serviceagent/DocumentManagementSystemEndpoint1/Downlo" +
            "adDocument", Name="Error", Namespace="http://www.tibco.com/schemas/ism-document-management-service/SharedResources/Sche" +
            "mas/Error.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GoDurban.SharepointService.DownloadDocumentResponse DownloadDocument(GoDurban.SharepointService.DownloadDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/webservice/Service/Service.serviceagent/DocumentManagementSystemEndpoint1/Downlo" +
            "adDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<GoDurban.SharepointService.DownloadDocumentResponse> DownloadDocumentAsync(GoDurban.SharepointService.DownloadDocumentRequest request);
        
        // CODEGEN: Generating message contract since the operation DeleteDocument is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/webservice/Service/Service.serviceagent//DeleteDocument", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(GoDurban.SharepointService.Error_T), Action="/webservice/Service/Service.serviceagent//DeleteDocument", Name="Error", Namespace="http://www.tibco.com/schemas/ism-document-management-service/SharedResources/Sche" +
            "mas/Error.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GoDurban.SharepointService.DeleteDocumentResponse DeleteDocument(GoDurban.SharepointService.DeleteDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/webservice/Service/Service.serviceagent//DeleteDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<GoDurban.SharepointService.DeleteDocumentResponse> DeleteDocumentAsync(GoDurban.SharepointService.DeleteDocumentRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tibco.com/schemas/ism-document-management-service/SharedResources/Sche" +
        "mas/Upload_Request.xsd")]
    public partial class Upload_Request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fileNameField;
        
        private string sourceLocationField;
        
        private string destinationLocationField;
        
        private string referenceNoField;
        
        private string descriptionField;
        
        private byte[] fileContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sourceLocation {
            get {
                return this.sourceLocationField;
            }
            set {
                this.sourceLocationField = value;
                this.RaisePropertyChanged("sourceLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string destinationLocation {
            get {
                return this.destinationLocationField;
            }
            set {
                this.destinationLocationField = value;
                this.RaisePropertyChanged("destinationLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string referenceNo {
            get {
                return this.referenceNoField;
            }
            set {
                this.referenceNoField = value;
                this.RaisePropertyChanged("referenceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=5)]
        public byte[] fileContent {
            get {
                return this.fileContentField;
            }
            set {
                this.fileContentField = value;
                this.RaisePropertyChanged("fileContent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tibco.com/schemas/ism-document-management-service/SharedResources/Sche" +
        "mas/Upload_Response.xsd")]
    public partial class Upload_Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string optStatusField;
        
        private string destinationURLField;
        
        private Upload_ResponseUpladDetails upladDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string optStatus {
            get {
                return this.optStatusField;
            }
            set {
                this.optStatusField = value;
                this.RaisePropertyChanged("optStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string destinationURL {
            get {
                return this.destinationURLField;
            }
            set {
                this.destinationURLField = value;
                this.RaisePropertyChanged("destinationURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Upload_ResponseUpladDetails UpladDetails {
            get {
                return this.upladDetailsField;
            }
            set {
                this.upladDetailsField = value;
                this.RaisePropertyChanged("UpladDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tibco.com/schemas/ism-document-management-service/SharedResources/Sche" +
        "mas/Upload_Response.xsd")]
    public partial class Upload_ResponseUpladDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Upload_ResponseUpladDetailsUploadResult uploadResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Upload_ResponseUpladDetailsUploadResult UploadResult {
            get {
                return this.uploadResultField;
            }
            set {
                this.uploadResultField = value;
                this.RaisePropertyChanged("UploadResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tibco.com/schemas/ism-document-management-service/SharedResources/Sche" +
        "mas/Upload_Response.xsd")]
    public partial class Upload_ResponseUpladDetailsUploadResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string link_urlField;
        
        private string createdByField;
        
        private string creation_DateField;
        
        private string object_IDField;
        
        private string reference_NumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string link_url {
            get {
                return this.link_urlField;
            }
            set {
                this.link_urlField = value;
                this.RaisePropertyChanged("link_url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string createdBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("createdBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string creation_Date {
            get {
                return this.creation_DateField;
            }
            set {
                this.creation_DateField = value;
                this.RaisePropertyChanged("creation_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string object_ID {
            get {
                return this.object_IDField;
            }
            set {
                this.object_IDField = value;
                this.RaisePropertyChanged("object_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string reference_Number {
            get {
                return this.reference_NumberField;
            }
            set {
                this.reference_NumberField = value;
                this.RaisePropertyChanged("reference_Number");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.tibco.com/schemas/ism-document-management-service/SharedResources/Sche" +
            "mas/Upload_Request.xsd", Order=0)]
        public GoDurban.SharepointService.Upload_Request Upload_Request;
        
        public UploadDocumentRequest() {
        }
        
        public UploadDocumentRequest(GoDurban.SharepointService.Upload_Request Upload_Request) {
            this.Upload_Request = Upload_Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.tibco.com/schemas/ism-document-management-service/SharedResources/Sche" +
            "mas/Upload_Response.xsd", Order=0)]
        public GoDurban.SharepointService.Upload_Response Upload_Response;
        
        public UploadDocumentResponse() {
        }
        
        public UploadDocumentResponse(GoDurban.SharepointService.Upload_Response Upload_Response) {
            this.Upload_Response = Upload_Response;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tibco.com/schemas/ism-document-management-service/SharedResources/Sche" +
        "mas/Search_Request.xsd")]
    public partial class Search_Request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string folderNameField;
        
        private string documentNameField;
        
        private string refNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FolderName {
            get {
                return this.folderNameField;
            }
            set {
                this.folderNameField = value;
                this.RaisePropertyChanged("FolderName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string documentName {
            get {
                return this.documentNameField;
            }
            set {
                this.documentNameField = value;
                this.RaisePropertyChanged("documentName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string refNo {
            get {
                return this.refNoField;
            }
            set {
                this.refNoField = value;
                this.RaisePropertyChanged("refNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tibco.com/schemas/ism-document-management-service/SharedResources/Sche" +
        "mas/Search_Response.xsd")]
    public partial class SearchDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bASE_TYPE_IDField;
        
        private string cREATION_DATEField;
        
        private string link_URLField;
        
        private string nAMEField;
        
        private string oBJECT_IDField;
        
        private string rEFERENCE_NUMBERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BASE_TYPE_ID {
            get {
                return this.bASE_TYPE_IDField;
            }
            set {
                this.bASE_TYPE_IDField = value;
                this.RaisePropertyChanged("BASE_TYPE_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CREATION_DATE {
            get {
                return this.cREATION_DATEField;
            }
            set {
                this.cREATION_DATEField = value;
                this.RaisePropertyChanged("CREATION_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Link_URL {
            get {
                return this.link_URLField;
            }
            set {
                this.link_URLField = value;
                this.RaisePropertyChanged("Link_URL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
                this.RaisePropertyChanged("NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string OBJECT_ID {
            get {
                return this.oBJECT_IDField;
            }
            set {
                this.oBJECT_IDField = value;
                this.RaisePropertyChanged("OBJECT_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string REFERENCE_NUMBER {
            get {
                return this.rEFERENCE_NUMBERField;
            }
            set {
                this.rEFERENCE_NUMBERField = value;
                this.RaisePropertyChanged("REFERENCE_NUMBER");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.tibco.com/schemas/ism-document-management-service/SharedResources/Sche" +
            "mas/Search_Request.xsd", Order=0)]
        public GoDurban.SharepointService.Search_Request Search_Request;
        
        public SearchDocumentRequest() {
        }
        
        public SearchDocumentRequest(GoDurban.SharepointService.Search_Request Search_Request) {
            this.Search_Request = Search_Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.tibco.com/schemas/ism-document-management-service/SharedResources/Sche" +
            "mas/Search_Response.xsd", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SearchDetails", IsNullable=false)]
        public GoDurban.SharepointService.SearchDetails[] response;
        
        public SearchDocumentResponse() {
        }
        
        public SearchDocumentResponse(GoDurban.SharepointService.SearchDetails[] response) {
            this.response = response;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tibco.com/schemas/ism-document-management-service/SharedResources/Sche" +
        "mas/Download_Request.xsd")]
    public partial class download_Request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string docNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string docName {
            get {
                return this.docNameField;
            }
            set {
                this.docNameField = value;
                this.RaisePropertyChanged("docName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tibco.com/schemas/ism-document-management-service/SharedResources/Sche" +
        "mas/Download_Response.xsd")]
    public partial class download_Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string optResultField;
        
        private string docNameField;
        
        private download_ResponseDownloadDetails downloadDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string optResult {
            get {
                return this.optResultField;
            }
            set {
                this.optResultField = value;
                this.RaisePropertyChanged("optResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string docName {
            get {
                return this.docNameField;
            }
            set {
                this.docNameField = value;
                this.RaisePropertyChanged("docName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public download_ResponseDownloadDetails downloadDetails {
            get {
                return this.downloadDetailsField;
            }
            set {
                this.downloadDetailsField = value;
                this.RaisePropertyChanged("downloadDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tibco.com/schemas/ism-document-management-service/SharedResources/Sche" +
        "mas/Download_Response.xsd")]
    public partial class download_ResponseDownloadDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string documentContentField;
        
        private string filenameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string documentContent {
            get {
                return this.documentContentField;
            }
            set {
                this.documentContentField = value;
                this.RaisePropertyChanged("documentContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
                this.RaisePropertyChanged("filename");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.tibco.com/schemas/ism-document-management-service/SharedResources/Sche" +
            "mas/Download_Request.xsd", Order=0)]
        public GoDurban.SharepointService.download_Request download_Request;
        
        public DownloadDocumentRequest() {
        }
        
        public DownloadDocumentRequest(GoDurban.SharepointService.download_Request download_Request) {
            this.download_Request = download_Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.tibco.com/schemas/ism-document-management-service/SharedResources/Sche" +
            "mas/Download_Response.xsd", Order=0)]
        public GoDurban.SharepointService.download_Response download_Response;
        
        public DownloadDocumentResponse() {
        }
        
        public DownloadDocumentResponse(GoDurban.SharepointService.download_Response download_Response) {
            this.download_Response = download_Response;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tibco.com/schemas/ism-dms/SharedResources/Schemas/Delete.xsd")]
    public partial class DeleteRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string documentNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string documentName {
            get {
                return this.documentNameField;
            }
            set {
                this.documentNameField = value;
                this.RaisePropertyChanged("documentName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tibco.com/schemas/ism-dms/SharedResources/Schemas/Delete.xsd")]
    public partial class DeleteResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.tibco.com/schemas/ism-dms/SharedResources/Schemas/Delete.xsd", Order=0)]
        public GoDurban.SharepointService.DeleteRequest DeleteRequest;
        
        public DeleteDocumentRequest() {
        }
        
        public DeleteDocumentRequest(GoDurban.SharepointService.DeleteRequest DeleteRequest) {
            this.DeleteRequest = DeleteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.tibco.com/schemas/ism-dms/SharedResources/Schemas/Delete.xsd", Order=0)]
        public GoDurban.SharepointService.DeleteResponse DeleteResponse;
        
        public DeleteDocumentResponse() {
        }
        
        public DeleteDocumentResponse(GoDurban.SharepointService.DeleteResponse DeleteResponse) {
            this.DeleteResponse = DeleteResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DocumentManagementSystemChannel : GoDurban.SharepointService.DocumentManagementSystem, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentManagementSystemClient : System.ServiceModel.ClientBase<GoDurban.SharepointService.DocumentManagementSystem>, GoDurban.SharepointService.DocumentManagementSystem {
        
        public DocumentManagementSystemClient() {
        }
        
        public DocumentManagementSystemClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentManagementSystemClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentManagementSystemClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentManagementSystemClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoDurban.SharepointService.UploadDocumentResponse GoDurban.SharepointService.DocumentManagementSystem.UploadDocument(GoDurban.SharepointService.UploadDocumentRequest request) {
            return base.Channel.UploadDocument(request);
        }
        
        public GoDurban.SharepointService.Upload_Response UploadDocument(GoDurban.SharepointService.Upload_Request Upload_Request) {
            GoDurban.SharepointService.UploadDocumentRequest inValue = new GoDurban.SharepointService.UploadDocumentRequest();
            inValue.Upload_Request = Upload_Request;
            GoDurban.SharepointService.UploadDocumentResponse retVal = ((GoDurban.SharepointService.DocumentManagementSystem)(this)).UploadDocument(inValue);
            return retVal.Upload_Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GoDurban.SharepointService.UploadDocumentResponse> GoDurban.SharepointService.DocumentManagementSystem.UploadDocumentAsync(GoDurban.SharepointService.UploadDocumentRequest request) {
            return base.Channel.UploadDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<GoDurban.SharepointService.UploadDocumentResponse> UploadDocumentAsync(GoDurban.SharepointService.Upload_Request Upload_Request) {
            GoDurban.SharepointService.UploadDocumentRequest inValue = new GoDurban.SharepointService.UploadDocumentRequest();
            inValue.Upload_Request = Upload_Request;
            return ((GoDurban.SharepointService.DocumentManagementSystem)(this)).UploadDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoDurban.SharepointService.SearchDocumentResponse GoDurban.SharepointService.DocumentManagementSystem.SearchDocument(GoDurban.SharepointService.SearchDocumentRequest request) {
            return base.Channel.SearchDocument(request);
        }
        
        public GoDurban.SharepointService.SearchDetails[] SearchDocument(GoDurban.SharepointService.Search_Request Search_Request) {
            GoDurban.SharepointService.SearchDocumentRequest inValue = new GoDurban.SharepointService.SearchDocumentRequest();
            inValue.Search_Request = Search_Request;
            GoDurban.SharepointService.SearchDocumentResponse retVal = ((GoDurban.SharepointService.DocumentManagementSystem)(this)).SearchDocument(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GoDurban.SharepointService.SearchDocumentResponse> GoDurban.SharepointService.DocumentManagementSystem.SearchDocumentAsync(GoDurban.SharepointService.SearchDocumentRequest request) {
            return base.Channel.SearchDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<GoDurban.SharepointService.SearchDocumentResponse> SearchDocumentAsync(GoDurban.SharepointService.Search_Request Search_Request) {
            GoDurban.SharepointService.SearchDocumentRequest inValue = new GoDurban.SharepointService.SearchDocumentRequest();
            inValue.Search_Request = Search_Request;
            return ((GoDurban.SharepointService.DocumentManagementSystem)(this)).SearchDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoDurban.SharepointService.DownloadDocumentResponse GoDurban.SharepointService.DocumentManagementSystem.DownloadDocument(GoDurban.SharepointService.DownloadDocumentRequest request) {
            return base.Channel.DownloadDocument(request);
        }
        
        public GoDurban.SharepointService.download_Response DownloadDocument(GoDurban.SharepointService.download_Request download_Request) {
            GoDurban.SharepointService.DownloadDocumentRequest inValue = new GoDurban.SharepointService.DownloadDocumentRequest();
            inValue.download_Request = download_Request;
            GoDurban.SharepointService.DownloadDocumentResponse retVal = ((GoDurban.SharepointService.DocumentManagementSystem)(this)).DownloadDocument(inValue);
            return retVal.download_Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GoDurban.SharepointService.DownloadDocumentResponse> GoDurban.SharepointService.DocumentManagementSystem.DownloadDocumentAsync(GoDurban.SharepointService.DownloadDocumentRequest request) {
            return base.Channel.DownloadDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<GoDurban.SharepointService.DownloadDocumentResponse> DownloadDocumentAsync(GoDurban.SharepointService.download_Request download_Request) {
            GoDurban.SharepointService.DownloadDocumentRequest inValue = new GoDurban.SharepointService.DownloadDocumentRequest();
            inValue.download_Request = download_Request;
            return ((GoDurban.SharepointService.DocumentManagementSystem)(this)).DownloadDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoDurban.SharepointService.DeleteDocumentResponse GoDurban.SharepointService.DocumentManagementSystem.DeleteDocument(GoDurban.SharepointService.DeleteDocumentRequest request) {
            return base.Channel.DeleteDocument(request);
        }
        
        public GoDurban.SharepointService.DeleteResponse DeleteDocument(GoDurban.SharepointService.DeleteRequest DeleteRequest) {
            GoDurban.SharepointService.DeleteDocumentRequest inValue = new GoDurban.SharepointService.DeleteDocumentRequest();
            inValue.DeleteRequest = DeleteRequest;
            GoDurban.SharepointService.DeleteDocumentResponse retVal = ((GoDurban.SharepointService.DocumentManagementSystem)(this)).DeleteDocument(inValue);
            return retVal.DeleteResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GoDurban.SharepointService.DeleteDocumentResponse> GoDurban.SharepointService.DocumentManagementSystem.DeleteDocumentAsync(GoDurban.SharepointService.DeleteDocumentRequest request) {
            return base.Channel.DeleteDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<GoDurban.SharepointService.DeleteDocumentResponse> DeleteDocumentAsync(GoDurban.SharepointService.DeleteRequest DeleteRequest) {
            GoDurban.SharepointService.DeleteDocumentRequest inValue = new GoDurban.SharepointService.DeleteDocumentRequest();
            inValue.DeleteRequest = DeleteRequest;
            return ((GoDurban.SharepointService.DocumentManagementSystem)(this)).DeleteDocumentAsync(inValue);
        }
    }
}
